apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uz1h92ftn-go
  janus-idp.io/tekton: uz1h92ftn-go
  backstage.io/kubernetes-id: uz1h92ftn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uz1h92ftn-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
