apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uz1h92ftn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uz1h92ftn-go 
  name: uz1h92ftn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uz1h92ftn-go 
