apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: uz1h92ftn-go-gitops
  description: This is GitOps manifest for uz1h92ftn-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: uz1h92ftn-go
    backstage.io/kubernetes-id: uz1h92ftn-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: uz1h92ftn-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:uz1h92ftn-go
